Repository Code-Odyssey-Editor/website, pull requests merged in 2023-11, with the labels that each got.

#19 Patch - 0.0.2 - Navbar UI Complete
  package-lock.json
  package.json
  src/App.tsx
  src/components/navbar/navbar.tsx
  src/components/theme_switcher/moon_icon.tsx
  src/components/theme_switcher/sun_icon.tsx
  src/components/theme_switcher/theme_toggle.tsx
Labels: enhancement

#41 Patch - 0.0.6 Fix Refresh Page and Other Issues
  404.html
  index.html
  src/App.tsx
Labels: bug

#47 Signin page succesfully updated
  src/pages/auth/signinpage.css
  src/pages/auth/signinpage.tsx
Labels: frontend

#52 Patch 0.0.7 - Add Support Page
  src/App.tsx
  src/components/footer/footer.tsx
  src/components/navbar/common_navbar.tsx
  src/components/support_box/box.tsx
  src/pages/supportpage.tsx
Labels: patch release

#59 Update the simple css file to tailwind css
  src/components/contact_box/contact.css
  src/components/contact_box/contact.tsx
Labels: bug, enhancement, good first issue, frontend

#72 Fix the warning in signinpage
  src/pages/auth/signinpage.tsx
Labels: bug
